blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainb/', include('mainb.urls')),
    path('mainb/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='blog.html'), name='home'),
    # path('accounts/', include('django.contrib.auth.urls')),
    #    path('', RedirectView.as_view(url='mainb/')),
    # ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # this will start url at /mainb/
]

mainb/urls.py
from django.urls import path, include
from . import views
from .views import SignUpView

urlpatterns = [
    path('', views.index, name='blog'),
    path('posts/', views.BlogPostListView.as_view(), name='all-posts'),
    path('post/<int:pk>', views.BlogPostDetailView.as_view(), name='view-post'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('topics/', views.TopicListView.as_view(), name='topics'),
    path('topics/<int:pk>', views.TopicDetailView.as_view(), name='topic-detail'),
    path('myposts/', views.PostedByAuthorListView.as_view(), name='my-posted'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

mainb/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, User
from django.db import models


class Author(models.Model):
    user_name = models.CharField(max_length=80, help_text='Enter your username')
    email = models.EmailField(max_length=100, help_text='Enter your email')
    first_name = models.CharField(max_length=100, help_text='Enter your first name')
    last_name = models.CharField(max_length=100, help_text='Enter your last name')

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return self.user_name


class BlogPost(models.Model):
    title = models.CharField(max_length=200, help_text='Enter the post title')
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    main_text = models.TextField(max_length=15000, help_text='Write what you think')
    topic = models.ManyToManyField('Topic', help_text='Select a topic for the post')
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4,
    # help_text="Unique ID for this particular post across the site")
    # posted date
    posted = models.DateField(auto_now=True)

    @property
    def number_comments(self):
        return BlogComment.objects.filter(com_title=self).count()

    def get_absolute_url(self):
        return reverse('view-post', args=[str(self.id)])

    def __str__(self):
        return self.title

    def display_topic(self):
        return ', '.join([topic.name for topic in self.topic.all()[:3]])

    display_topic.short_description = 'Topic'


class Topic(models.Model):
    name = models.CharField(max_length=50, help_text='Enter a post topic')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('topic-detail', args=[str(self.id)])


class CustomUser(AbstractUser):
    pass

    # add additional fields in here

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class BlogComment(models.Model):
    com_title = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.author) + ', ' + self.com_title.title[:40]

mainb/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, BlogPost, BlogComment
from django.forms import ModelForm, TextInput


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ['topic', 'title', 'main_text']
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Title'
            }),
            'topic': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Topic'
            }),
            'main_text': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your text...'
                })
        }


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ['content']

mainb/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import BlogPost, Topic, Author, BlogComment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from .forms import CustomUserCreationForm, BlogPostForm, NewCommentForm


# a function based view
def index(request):
    num_posts = BlogPost.objects.all().count()
    num_authors = Author.objects.all().count()
    num_topics = Topic.objects.count()
    context = {
        'num_posts': num_posts,
        'num_authors': num_authors,
        'num_topics': num_topics,
    }
    return render(request, 'blog.html', context=context)


class PostedByAuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    template_name = 'mainb/author_list_posted.html'

    def get_queryset(self):
        return Author.objects.filter(posted=self.request.user)


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class BlogPostListView(generic.ListView):
    model = BlogPost
    # context_object_name = 'post_list'


class BlogPostDetailView(generic.DetailView):
    model = BlogPost

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        com_title = BlogComment.objects.filter(
            com_title=self.get_object()).order_by('-date_posted')
        data['comments'] = com_title
        if self.request.user.is_authenticated:
            data['comment_form'] = NewCommentForm(instance=self.request.user)

        return data

    def post(self, request, *args, **kwargs):
        new_comment = BlogComment(content=request.POST.get('content'),
                                  author=self.request.user,
                                  com_title=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


class TopicDetailView(generic.DetailView):
    model = Topic


class TopicListView(generic.ListView):
    model = Topic

mainb/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Blog</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'blog' %}">Home</a></li>
                <li><a href="{% url 'all-posts' %}">All posts</a></li>
                <li><a href="{% url 'authors' %}">All authors</a></li>
                <li><a href="{% url 'topics' %}">All topics</a></li>
                {% if user.is_authenticated %}
                    <li>Hello, {{ user.get_username }} !</li>
                   <!-- <li><a href=" {% url 'create' %}">Create a post</a></li> -->
                <!-- {{ request.path }} to redirect to a page where 'login' was pressed -->
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    <li> <a href="{% url 'signup' %}">Sign Up</a></li>
                {% endif %}

            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10"> {% block content %}{% endblock %}</div>
    </div>
</div>
</body>
</html>

mainb/templates/blog.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blog main page</h1>
<p>Welcome to the <em>test blog website</em>!</p>

{% endblock %}

mainb/templates/mainb/BlogPost_detail.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Title: {{ object.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ object.author.get_absolute_url }}"> {{ object.author }} </a></p>
  <p><strong>Topic:</strong> <a href="{{ object.topic.get_absolute_url }}">{{ object.topic.all|join:", " }}</a></p>
  <p>{{object.main_text }}</p>


<p><strong>Leave your comment!</strong></p>
<div id="comments_section">

  {% if user.is_authenticated %}
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{ comment_form }}
      <button class="btn btn-info" type="submit">Add comment <i class="fas fa-comments"></i></button>
    </div>
  </form>
  {% else %}
  <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to add a comment!</a><br>
  {% endif %}

  {% if comments %}
  <strong class="text-secondary">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong>
  <hr>
  <ul>
    {% for comment in comments %}
    <li>
     <div>
        <span>
          <strong class="text-info">{{ comment.author }} </strong>
          <small class="text-muted">{{ comment.date_posted }}</small>
        </span>
        <p>
          {{ comment.content|safe }}
        </p>
      </div>
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <strong class="text-secondary">No comments yet...</strong>
  {% endif %}
</div>
{% endblock %}

mainb/templates/mainb/BlogPost_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>List of posts</h1>
    {% if object_list %}
        <ul>
            {% for post in object_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>, by: {{ post.author }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts yet.</p>
    {% endif %}
{% endblock %}

mainb/templates/mainb/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
  <h2>Author details: {{ object.first_name }} {{object.last_name }}</h2>

<div style="margin-left:20px;margin-top:20px">
  <p><strong>User name: </strong>  {{ object.user_name }} </a></p>
  <p><strong>Full name :</strong> {{ object.first_name }} {{object.last_name }}</p>
  <h4>Posted: </h4>
  <d1>
    {% for post in author.blogpost_set.all %}
    <dt><a href="{% url 'view-post' post.pk %}">{{ post }}</a></dt>
    {% endfor %}
  </d1>

</div>
{% endblock %}

mainb/templates/mainb/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
        
        
{% endblock %}

mainb/templates/mainb/author_list_posted.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Posted by me:</h1>

    {% if author_list %}
    <ul>

      {% for post in author_list %}
        <a href="{{ author.get_absolute_url }}">
        <a href="{% url 'topic-detail' post.blogpost.pk %}">{{ post.blogpost.title }}</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are posts by me.</p>
    {% endif %}
{% endblock %}

mainb/templates/mainb/register.html
{% extends "base_generic.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
<div class="features">
<h3>Register here</h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <p>{{ field.label }}: <br> {{ field }}</p>

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    <button class="btn btn-success" type="submit">Register</button>
</form>
</div>
{% endblock %}

mainb/templates/mainb/topic_detail.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Posts:</h1>
        <ul>
            {% for post in topic.blogpost_set.all %}
                <li>
                    <a href="{% url 'view-post' post.pk %}">{{ post.title }} </a>
                </li>
            {% endfor %}
        </ul>
{% endblock %}

mainb/templates/mainb/topic_list.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Topics:</h1>
        <ul>
            {% for post in object_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.name }} </a>
                </li>
            {% endfor %}
        </ul>
{% endblock %}

templates/signup.html
{% extends "base_generic.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
<div class="features">
  <div class="container py-5">
  <h2>Sign up</h2>
    <form method="POST">
      {% csrf_token %}
       <label>{{ form.username.label }}</label>
        {{ form.username }}
        <label>{{ form.password1.label }}</label>
        {{ form.password1 }}
        <label>{{ form.password2.label }}</label>
        {{ form.password2 }}
      <br>
    <button class="btn btn-success" type="submit">Sign up</button>
  </form>
  </div>
</div>
{% endblock %}